-- create
CREATE TABLE SIMPLE_TABLE_NAME (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  adress TEXT NOT NULL
);

-- insert
INSERT INTO SIMPLE_TABLE_NAME VALUES (0001, 'name1', 11, 'adress1');
INSERT INTO SIMPLE_TABLE_NAME VALUES (0002, 'name2', 22, 'adress2');
INSERT INTO SIMPLE_TABLE_NAME VALUES (0003, 'name3', 33, 'adress3');

-- fetch 
SELECT * FROM SIMPLE_TABLE_NAME;
